language: node_js
node_js:
  - "8"
  - "7"
before_install:
  - sudo apt-get -y install libicu-dev
  - npm install -g npm
script:
  - "npm run-script lint"
  - "npm test"
  - "npm run-script cover"
after_success:
  - rm coverage.lcov
notifications:
  slack:
    - secure: "gPBKAtkXFoZo6+Q4J2VWTr0feYGXy6LFVNheoIE3mlsmIIRVFztUpImppF+L6bjopLxcNiicpTDBbvqRN+GqRXzKgnvRVteaV6Mbeoc8X4LQF90o4Wkzt08XvoHqtH/d1ZtJlrFTAwX8FzFtGCNpAA+8RkKeobvvzqcfwPnXupuzZJcmY0ft5hQGVXD3lU19n6JWxq81h1NKWq8EhjrJiL+sNuKgzqWgnKnQPB8dGaHR2I9/eGleJD38KS0Pk2/+uarTk/D05A3WBSL2yIDV2Hvy6JRE5vNHQJYkj9uqdbT2spBtq2Nn4xaqiz+70bkOe6GvanL0uw87ujVu3+AS0qFoHQy4CS+Y8UReCbrmg/T1kDxOTw2g+syFsqnvqYWbvbpCkGC5JHKSkD9YOKbYCGYL1Jih6Q8Qxqzhb7FzhceAjHD4KfLy9X39oFjXlUUP4NtsMAWd+G9Uft45+wkYAR/hSlmOpvBfQ9spmGGMeOVVUX/9kzATCM6WfG5sb4uU2d4vZfw6MQHKpKugT7GbRrrcCJL8mx4eJ0cibUJgLFyp2T60SKdqCXwy99AhzWhpRFt7fE/ZMOr/say73FLEBGBkgwntLkvQVuRZpu5wiRlUW46Rl2QnGgluqIMf5KJSjPk8sPiVkYS3oZ1hbLVvAQUHJ+ySRUdi2iZEEN8XR9I="
